name: Django CI

on:
  push:
    branches:
      - main  # Change this to your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Choose the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up PostgreSQL
      run: docker-compose -f ./docker-compose.yml up -d

    - name: Check Docker Compose Status
      run: docker-compose -f ./docker-compose.yml ps

    - name: Run Migrations for Tests
      run: python manage.py migrate

    - name: Run Tests
      run: python manage.py test